name: Python application

on:
  push:
    branches:
      - '**'  # This will run the workflow for any push to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your Python version here

      - name: Install dependencies using uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync

      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest
